#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
📝 Reporter-Agent - 记录员
报告生成与复盘
"""

import json
from pathlib import Path
from datetime import datetime

class ReporterAgent:
    """记录员 Agent - 报告生成专家"""
    
    def __init__(self, mission_data: dict, output_dir: str = None):
        self.mission = mission_data
        self.output_dir = Path(output_dir) if output_dir else Path("/tmp/reports")
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_report(self, format: str = "html") -> str:
        """生成渗透测试报告"""
        print("[📝] Reporter-Agent 生成报告中...")
        
        if format == "json":
            return self._generate_json_report()
        elif format == "html":
            return self._generate_html_report()
        else:
            return self._generate_json_report()
    
    def _generate_json_report(self) -> str:
        """生成 JSON 报告"""
        report = {
            "mission_id": self.mission.get("mission_id", "unknown"),
            "target": self.mission.get("target", "unknown"),
            "timestamp": datetime.utcnow().isoformat(),
            "findings": self.mission.get("findings", []),
            "recommendations": self.mission.get("recommendations", [])
        }
        
        report_file = self.output_dir / f"report_{self.mission.get('mission_id', 'unknown')}.json"
        with open(report_file, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
        
        print(f"    ✓ JSON 报告已保存：{report_file}")
        return str(report_file)
    
    def _generate_html_report(self) -> str:
        """生成 HTML 报告"""
        report_file = self.output_dir / f"report_{self.mission.get('mission_id', 'unknown')}.html"
        
        # 简化版 HTML 报告
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>渗透测试报告 - {self.mission.get('target', 'unknown')}</title>
</head>
<body>
    <h1>🔒 渗透测试报告</h1>
    <p><strong>任务 ID:</strong> {self.mission.get('mission_id', 'unknown')}</p>
    <p><strong>目标:</strong> {self.mission.get('target', 'unknown')}</p>
    <p><strong>时间:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    <hr>
    <h2>发现</h2>
    <p>共发现 {len(self.mission.get('findings', []))} 个问题</p>
    <hr>
    <p><em>Generated by ClawSec RedTeam Reporter-Agent</em></p>
</body>
</html>
"""
        
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write(html)
        
        print(f"    ✓ HTML 报告已保存：{report_file}")
        return str(report_file)
