name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.156.0'
          extended: true
      
      - name: Build
        run: hugo --minify
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: Ijb5MQFaqklcMtzD_qxSdSPCNPRCBlPslijY7PI-
          accountId: 538536fdc38937e7ff08f5aac3a6ffa7
          projectName: blog
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
